### ISSUE TITLE
[feat] 기존에 완성한 개인과제 가져오기

### ISSUE THREAD

**Issue by issuebombom** [issuebombom/team_project_vanilla_js#1]
# Description
각자 제출하신 개인 과제 중 하나를 선정하여 추가해주세요.  
index.html 안에 style과 script가 모두 들어있다면 html 파일 하나만, js파일과 css가 나눠져 있다면 모두 포함하여 push해주세요.
add - commit - push는 한 분이 대표로 진행해 주시면 됩니다.  

# TODO
- [ ] 개인 과제 선정하기
- [ ] git clone https://github.com/issuebombom/team_project_vanilla_js.git
- [ ] git checkout -b 브랜치 이름
- [ ] 개인 과제 파일 복사하기
- [ ] add - commit - push

# ETC
- commit 메시지 양식은 .gitmessage를 참조해 주세요.  
ex) 영화 API 기능 구현 시 커밋메세지를 아래와 같이 작성해주세요.
  > feat: 영화 데이터 수집 API 구현. 
  >
  > 영화 데이터 수집 API 기능 구현했습니다 코드리뷰 부탁드립니다.

- `git push origin 브랜치 이름`으로 push해주세요.
